# Generated by Django 3.2.19 on 2024-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_from_renewables', models.FloatField()),
                ('co2_emissions', models.FloatField()),
                ('renewables_percentage', models.FloatField()),
                ('gdp_growth', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
